#!/usr/bin/env bash

workdir=$(cd `dirname $0`; pwd)

docker-compose stop nginx

if [ "$1"x == renewx ] || [ "$1"x == x ]; then
    echo renew
    docker run --rm -p 80:80 -p 443:443 \
        -v $workdir/letsencrypt:/etc/letsencrypt \
        certbot/certbot:v0.19.0 renew \
        --standalone --force-renewal
else
    echo create
    docker run --rm -p 80:80 -p 443:443 \
        -v $workdir/letsencrypt:/etc/letsencrypt \
        certbot/certbot:v0.19.0 certonly \
        --standalone -m jibo@outlook.com --agree-tos \
        -d $2.syncxplus.com
fi
    
docker-compose start nginx
