version: '2'
services:
    gitlab:
        image: gitlab/gitlab-ce:9.1.2-ce.0
        restart: always
        hostname: git.syncxplus.com
        ports:
            - '22:22'
        volumes:
            - ./gitlab/config:/etc/gitlab
            - ./gitlab/data:/var/opt/gitlab
            - ./gitlab/logs:/var/log/gitlab
    nginx:
        image: registry.aliyuncs.com/syncxplus/nginx:1.11.13
        restart: always
        ports:
            - '80:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - gitlab
        links:
            - gitlab:gitlab
