version: '2'
services:
    nginx:
        image: registry.aliyuncs.com/syncxplus/nginx:1.11.10
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./letsencrypt:/etc/letsencrypt
        depends_on:
            - jenkins
            - rancher
        links:
            - jenkins:jenkins
            - rancher:rancher
    jenkins:
        image: jenkins:2.46.2
        restart: always
        ports:
            - '50000:50000'
        volumes:
            - ./jenkins:/var/jenkins_home
    rancher:
        image: rancher/server:v1.5.7
        restart: always
        ports:
            - '8080:8080'
