version: '2'
services:
    gitlab:
        image: gitlab/gitlab-ce:9.1.2-ce.0
        restart: always
        hostname: git.syncxplus.com
        ports:
            - '22:22'
        volumes:
            - ./gitlab/config:/etc/gitlab
            - ./gitlab/data:/var/opt/gitlab
            - ./gitlab/logs:/var/log/gitlab
    jenkins:
        image: jenkins:2.46.2
        restart: always
        environment:
            JAVA_OPTS: '-Duser.timezone=Asia/Shanghai'
        ports:
            - '50000:50000'
        volumes:
            - ./jenkins:/var/jenkins_home
    nginx:
        image: registry.aliyuncs.com/syncxplus/nginx:1.11.10
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./letsencrypt:/etc/letsencrypt
        depends_on:
            - gitlab
            - jenkins
        links:
            - gitlab:gitlab
            - jenkins:jenkins
