version: '2'
services:
    gitlab:
        image: 9.1.2-ce.0
        restart: always
        hostname: git.syncxplus.com
        ports:
            - '22:22'
        volumes:
            - ./gitlab/config:/etc/gitlab
            - ./gitlab/data:/var/opt/gitlab
            - ./gitlab/logs:/var/log/gitlab
    jenkins:
        image: jenkins:2.46.2
        restart: always
        ports:
            - '50000:50000'
        volumes:
            - ./jenkins:/var/jenkins_home
    elasticsearch:
        image: elasticsearch:2.4.4-alpine
        restart: always
        ports:
            - '9527:9200'
    kibana:
        image: kibana:4.6.4
        restart: always
        environment:
            ELASTICSEARCH_URL: 'http://elasticsearch:9200'
            NODE_OPTIONS: '--max-old-space-size=512'
        depends_on:
            - elasticsearch
        links:
            - elasticsearch:elasticsearch
    nginx:
        image: registry.aliyuncs.com/syncxplus/nginx:1.11.10
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./letsencrypt:/etc/letsencrypt
        depends_on:
            - gitlab
            - jenkins
            - kibana
        links:
            - gitlab:gitlab
            - jenkins:jenkins
            - kibana:kibana
