version: '2'
services:
    gitlab:
        image: gitlab/gitlab-ce:9.1.2-ce.0
        restart: always
        hostname: git.syncxplus.com
        ports:
            - '22:22'
        volumes:
            - ./gitlab/config:/etc/gitlab
            - ./gitlab/data:/var/opt/gitlab
            - ./gitlab/logs:/var/log/gitlab
    jenkins:
        image: jenkins/jenkins:2.135
        restart: always
        environment:
            JAVA_OPTS: '-Duser.timezone=Asia/Shanghai'
        ports:
            - '50000:50000'
        volumes:
            - ./jenkins:/var/jenkins_home
    memcached:
        image: memcached:1.4.36-alpine
        restart: always
    postgres:
        image: postgres:9.6.3-alpine
        restart: always
        environment:
            - POSTGRES_USER=reviewboard
        volumes:
            - ./postgres:/var/lib/postgresql/data
    reviewboard:
        image: ikatson/reviewboard
        restart: always
        volumes:
            - ./reviewboard/media:/media
            - ./reviewboard/ssh:/root/.ssh
            - ./reviewboard/www:/var/www/reviewboard
            - ./gitlab/data/git-data/repositories:/data
            - ./views.py:/usr/lib/python2.7/site-packages/djblets/feedview/views.py
        depends_on:
            - postgres
            - memcached
        environment:
            DOMAIN: rb.syncxplus.com
            MEMCACHED: memcached:11211
            PGHOST: postgres
            WAIT_FOR_POSTGRES: 'true'
    zentao:
        image: registry.aliyuncs.com/syncxplus/zentao:9.5.1
        restart: always
        volumes:
            - ./zentao/tmp:/var/www/tmp
            - ./zentao/config:/var/www/config
            - ./zentao/data:/var/www/www/data
    elasticsearch:
        image: elasticsearch:2.4.6-alpine
        restart: always
        ports:
            - '9527:9200'
    kibana:
        image: kibana:4.6.6
        restart: always
        environment:
            ELASTICSEARCH_URL: 'http://elasticsearch:9200'
            NODE_OPTIONS: '--max-old-space-size=256'
        depends_on:
            - elasticsearch
        links:
            - elasticsearch:elasticsearch
    nginx:
        image: registry.aliyuncs.com/syncxplus/nginx:1.11.13
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./letsencrypt:/etc/letsencrypt
        depends_on:
            - gitlab
            - jenkins
            - kibana
            - reviewboard
            - zentao
        links:
            - gitlab:gitlab
            - jenkins:jenkins
            - kibana
            - reviewboard:reviewboard
            - zentao:zentao
